/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints,
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.auth

import org.openapitools.client.ApiException
import org.openapitools.client.Pair
import java.net.URI
import javax.annotation.Generated

@Generated(value = ["org.openapitools.codegen.languages.JavaClientCodegen"], date = "2024-04-14T17:24:33.796785+08:00[Asia/Hong_Kong]", comments = "Generator version: 7.5.0-SNAPSHOT")
class ApiKeyAuth(val location: String, val paramName: String) : Authentication {
    var apiKey: String? = null
    var apiKeyPrefix: String? = null

    @Throws(ApiException::class)
    override fun applyToParams(queryParams: MutableList<Pair?>, headerParams: MutableMap<String?, String?>, cookieParams: MutableMap<String?, String?>,
                               payload: String?, method: String?, uri: URI?) {
        if (apiKey == null) {
            return
        }
        val value: String
        value = if (apiKeyPrefix != null) {
            "$apiKeyPrefix $apiKey"
        } else {
            apiKey
        }
        if ("query" == location) {
            queryParams.add(Pair(paramName, value))
        } else if ("header" == location) {
            headerParams[paramName] = value
        } else if ("cookie" == location) {
            cookieParams[paramName] = value
        }
    }
}
