/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints,
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.auth

import org.openapitools.client.ApiException
import org.openapitools.client.Pair
import java.net.URI

interface Authentication {
    /**
     * Apply authentication settings to header and query params.
     *
     * @param queryParams List of query parameters
     * @param headerParams Map of header parameters
     * @param cookieParams Map of cookie parameters
     * @param payload HTTP request body
     * @param method HTTP method
     * @param uri URI
     * @throws ApiException if failed to update the parameters
     */
    @Throws(ApiException::class)
    fun applyToParams(queryParams: MutableList<Pair?>, headerParams: MutableMap<String?, String?>, cookieParams: MutableMap<String?, String?>, payload: String?, method: String?, uri: URI?)
}
