/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints,
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.junit.jupiter.api.Test

/**
 * Model tests for Apple
 */
class AppleTest {
    private val model = Apple()

    /**
     * Model tests for Apple
     */
    @Test
    fun testApple() {
        // TODO: test Apple
    }

    /**
     * Test the property 'cultivar'
     */
    @Test
    fun cultivarTest() {
        // TODO: test cultivar
    }

    /**
     * Test the property 'origin'
     */
    @Test
    fun originTest() {
        // TODO: test origin
    }
}
