/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints,
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.junit.jupiter.api.Test

/**
 * Model tests for AppleReq
 */
class AppleReqTest {
    private val model = AppleReq()

    /**
     * Model tests for AppleReq
     */
    @Test
    fun testAppleReq() {
        // TODO: test AppleReq
    }

    /**
     * Test the property 'cultivar'
     */
    @Test
    fun cultivarTest() {
        // TODO: test cultivar
    }

    /**
     * Test the property 'mealy'
     */
    @Test
    fun mealyTest() {
        // TODO: test mealy
    }
}
