/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints,
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.junit.jupiter.api.Test

/**
 * Model tests for FruitReq
 */
class FruitReqTest {
    private val model = FruitReq()

    /**
     * Model tests for FruitReq
     */
    @Test
    fun testFruitReq() {
        // TODO: test FruitReq
    }

    /**
     * Test the property 'cultivar'
     */
    @Test
    fun cultivarTest() {
        // TODO: test cultivar
    }

    /**
     * Test the property 'mealy'
     */
    @Test
    fun mealyTest() {
        // TODO: test mealy
    }

    /**
     * Test the property 'lengthCm'
     */
    @Test
    fun lengthCmTest() {
        // TODO: test lengthCm
    }

    /**
     * Test the property 'sweet'
     */
    @Test
    fun sweetTest() {
        // TODO: test sweet
    }
}
