/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints,
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.junit.jupiter.api.Test

/**
 * Model tests for Pet
 */
class PetTest {
    private val model = Pet()

    /**
     * Model tests for Pet
     */
    @Test
    fun testPet() {
        // TODO: test Pet
    }

    /**
     * Test the property 'id'
     */
    @Test
    fun idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'category'
     */
    @Test
    fun categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'name'
     */
    @Test
    fun nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'photoUrls'
     */
    @Test
    fun photoUrlsTest() {
        // TODO: test photoUrls
    }

    /**
     * Test the property 'tags'
     */
    @Test
    fun tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'status'
     */
    @Test
    fun statusTest() {
        // TODO: test status
    }
}
