/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints,
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.junit.jupiter.api.Test

/**
 * Model tests for Tag
 */
class TagTest {
    private val model = Tag()

    /**
     * Model tests for Tag
     */
    @Test
    fun testTag() {
        // TODO: test Tag
    }

    /**
     * Test the property 'id'
     */
    @Test
    fun idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    fun nameTest() {
        // TODO: test name
    }
}
