/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints,
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.junit.jupiter.api.Test

/**
 * Model tests for Whale
 */
class WhaleTest {
    private val model = Whale()

    /**
     * Model tests for Whale
     */
    @Test
    fun testWhale() {
        // TODO: test Whale
    }

    /**
     * Test the property 'hasBaleen'
     */
    @Test
    fun hasBaleenTest() {
        // TODO: test hasBaleen
    }

    /**
     * Test the property 'hasTeeth'
     */
    @Test
    fun hasTeethTest() {
        // TODO: test hasTeeth
    }

    /**
     * Test the property 'className'
     */
    @Test
    fun classNameTest() {
        // TODO: test className
    }
}
