/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints,
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.junit.jupiter.api.Test

/**
 * Model tests for Zebra
 */
class ZebraTest {
    private val model = Zebra()

    /**
     * Model tests for Zebra
     */
    @Test
    fun testZebra() {
        // TODO: test Zebra
    }

    /**
     * Test the property 'type'
     */
    @Test
    fun typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'className'
     */
    @Test
    fun classNameTest() {
        // TODO: test className
    }
}
