/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints,
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client

/**
 * API response returned by API call.
 */
class ApiResponse<T> @JvmOverloads constructor(
        /**
         *
         * Get the `status code`.
         *
         * @return the status code
         */
        val statusCode: Int,
        /**
         *
         * Get the `headers`.
         *
         * @return a [java.util.Map] of headers
         */
        val headers: Map<String, List<String>>, data: T? = null) {
    /**
     *
     * Get the `data`.
     *
     * @return the data
     */
    val data: T
    /**
     *
     * Constructor for ApiResponse.
     *
     * @param statusCode The status code of HTTP response
     * @param headers The headers of HTTP response
     * @param data The object deserialized from response bod
     */
    /**
     *
     * Constructor for ApiResponse.
     *
     * @param statusCode The status code of HTTP response
     * @param headers The headers of HTTP response
     */
    init {
        this.data = data
    }
}
