/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints,
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client

import javax.annotation.Generated

@Generated(value = ["org.openapitools.codegen.languages.JavaClientCodegen"], date = "2024-04-14T17:24:33.796785+08:00[Asia/Hong_Kong]", comments = "Generator version: 7.5.0-SNAPSHOT")
class Pair(name: String, value: String?) {
    var name = ""
        private set(name) {
            if (!isValidString(name)) {
                return
            }
            field = name
        }
    var value: String? = ""
        private set(value) {
            if (!isValidString(value)) {
                return
            }
            field = value
        }

    init {
        this.name = name
        this.value = value
    }

    private fun isValidString(arg: String?): Boolean {
        return if (arg == null) {
            false
        } else true
    }
}
