/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints,
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import com.google.gson.Gson
import com.google.gson.JsonElement
import com.google.gson.TypeAdapter
import com.google.gson.TypeAdapterFactory
import com.google.gson.annotations.SerializedName
import com.google.gson.reflect.TypeToken
import com.google.gson.stream.JsonReader
import com.google.gson.stream.JsonWriter
import org.openapitools.client.JSON
import java.io.IOException
import java.math.BigDecimal
import java.util.Objects
import javax.annotation.Generated

/**
 * BananaReq
 */
@Generated(value = ["org.openapitools.codegen.languages.JavaClientCodegen"], date = "2024-04-14T17:24:37.248933300+08:00[Asia/Hong_Kong]", comments = "Generator version: 7.5.0-SNAPSHOT")
class BananaReq {
    /**
     * Get lengthCm
     * @return lengthCm
     */
    @get:Nonnull
    @SerializedName(SERIALIZED_NAME_LENGTH_CM)
    var lengthCm: BigDecimal? = null

    /**
     * Get sweet
     * @return sweet
     */
    @SerializedName(SERIALIZED_NAME_SWEET)
    var sweet: Boolean? = null
    fun lengthCm(lengthCm: BigDecimal?): BananaReq {
        this.lengthCm = lengthCm
        return this
    }

    fun sweet(sweet: Boolean?): BananaReq {
        this.sweet = sweet
        return this
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val bananaReq = o as BananaReq
        return lengthCm == bananaReq.lengthCm && sweet == bananaReq.sweet
    }

    override fun hashCode(): Int {
        return Objects.hash(lengthCm, sweet)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class BananaReq {\n")
        sb.append("    lengthCm: ").append(toIndentedString(lengthCm)).append("\n")
        sb.append("    sweet: ").append(toIndentedString(sweet)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }

    class CustomTypeAdapterFactory : TypeAdapterFactory {
        override fun <T> create(gson: Gson, type: TypeToken<T>): TypeAdapter<T> {
            if (!BananaReq::class.java.isAssignableFrom(type.rawType)) {
                return null // this class only serializes 'BananaReq' and its subtypes
            }
            val elementAdapter = gson.getAdapter(JsonElement::class.java)
            val thisAdapter = gson.getDelegateAdapter(this, TypeToken.get(BananaReq::class.java))
            return object : TypeAdapter<BananaReq>() {
                @Throws(IOException::class)
                override fun write(out: JsonWriter, value: BananaReq) {
                    val obj = thisAdapter.toJsonTree(value).getAsJsonObject()
                    elementAdapter.write(out, obj)
                }

                @Throws(IOException::class)
                override fun read(`in`: JsonReader): BananaReq {
                    val jsonElement = elementAdapter.read(`in`)
                    validateJsonElement(jsonElement)
                    return thisAdapter.fromJsonTree(jsonElement)
                }
            }.nullSafe() as TypeAdapter<T>
        }
    }

    /**
     * Convert an instance of BananaReq to an JSON string
     *
     * @return JSON string
     */
    fun toJson(): String {
        return JSON.getGson().toJson(this)
    }

    companion object {
        const val SERIALIZED_NAME_LENGTH_CM = "lengthCm"
        const val SERIALIZED_NAME_SWEET = "sweet"
        var openapiFields: HashSet<String>? = null
        var openapiRequiredFields: HashSet<String>? = null

        init {
            // a set of all properties/fields (JSON key names)
            openapiFields = HashSet()
            openapiFields!!.add("lengthCm")
            openapiFields!!.add("sweet")

            // a set of required properties/fields (JSON key names)
            openapiRequiredFields = HashSet()
            openapiRequiredFields!!.add("lengthCm")
        }

        /**
         * Validates the JSON Element and throws an exception if issues found
         *
         * @param jsonElement JSON Element
         * @throws IOException if the JSON Element is invalid with respect to BananaReq
         */
        @Throws(IOException::class)
        fun validateJsonElement(jsonElement: JsonElement?) {
            if (jsonElement == null) {
                require(openapiRequiredFields!!.isEmpty()) {  // has required fields but JSON element is null
                    String.format("The required field(s) %s in BananaReq is not found in the empty JSON string", openapiRequiredFields.toString())
                }
            }
            val entries = jsonElement!!.getAsJsonObject().entrySet()
            // check to see if the JSON string contains additional fields
            for ((key) in entries) {
                require(openapiFields!!.contains(key)) { String.format("The field `%s` in the JSON string is not defined in the `BananaReq` properties. JSON: %s", key, jsonElement.toString()) }
            }

            // check to make sure all required properties/fields are present in the JSON string
            for (requiredField in openapiRequiredFields!!) {
                requireNotNull(jsonElement.getAsJsonObject()[requiredField]) { String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()) }
            }
            val jsonObj = jsonElement.getAsJsonObject()
        }

        /**
         * Create an instance of BananaReq given an JSON string
         *
         * @param jsonString JSON string
         * @return An instance of BananaReq
         * @throws IOException if the JSON string is invalid with respect to BananaReq
         */
        @Throws(IOException::class)
        fun fromJson(jsonString: String?): BananaReq {
            return JSON.getGson().fromJson(jsonString, BananaReq::class.java)
        }
    }
}
