/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints,
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.openapitools.client.ApiException

/**
 * API tests for DefaultApi
 */
@Disabled
class DefaultApiTest {
    private val api = DefaultApi()

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    @Throws(ApiException::class)
    fun fooGetTest() {
        api.fooGet()
        // TODO: test validations
    }
}
